export const UNIVERSE_AGE_GYR = 13.8;

// The seven bands follow Chaisson's explanatory sequence, but the underlying
// processes overlap. ageStart/ageEnd are therefore camera/timeline anchors,
// not claims that nature switches one process off when the next begins.
export const EPOCHS = [
  {
    id: 'particle',
    name: 'Particle Epoch',
    subtitle: 'Simplicity Fleeting',
    ageStart: 0,
    ageEnd: 0.00038,
    ageMap: 'log-early',
    focus: 'hot plasma → neutral atoms',
    erd: 0.02,
    description: 'The universe expands and cools from an extremely hot, dense plasma. Light nuclei form in the first minutes. About 380,000 years after the Big Bang, electrons bind to nuclei, the plasma becomes mostly neutral, and the cosmic microwave background is released.',
    principles: ['expansion + cooling', 'light-element nucleosynthesis', 'recombination ≈ 380 kyr', 'CMB release'],
  },
  {
    id: 'galactic',
    name: 'Galactic Epoch',
    subtitle: 'Hierarchy of Structures',
    ageStart: 0.00038,
    ageEnd: 0.12,
    focus: 'dark-matter halos + protogalactic structure',
    erd: 0.35,
    description: 'Tiny primordial density fluctuations grow under gravity. In the standard ΛCDM picture, dark matter provides gravitational scaffolding while ordinary gas falls into the deepest potential wells. These early halos and filaments become the environments in which the first stars and galaxies assemble.',
    principles: ['primordial fluctuations', 'ΛCDM gravity', 'cosmic web', 'hierarchical assembly'],
  },
  {
    id: 'stellar',
    name: 'Stellar Epoch',
    subtitle: 'Forges for Elements',
    ageStart: 0.12,
    ageEnd: 9.20,
    focus: 'stars + chemical enrichment',
    erd: 1,
    description: 'The first stars likely ignite roughly 100–200 million years after the Big Bang, while galaxy assembly continues around them. Stellar fusion builds elements through iron; winds, supernovae, neutron-star mergers, and other explosive events distribute many heavier nuclei and progressively enrich later generations of gas.',
    principles: ['gas-cloud collapse', 'fusion + feedback', 'stellar lifecycles', 'multi-site nucleosynthesis'],
  },
  {
    id: 'planetary',
    name: 'Planetary Epoch',
    subtitle: 'Habitats for Life',
    ageStart: 9.20,
    ageEnd: 9.30,
    focus: 'Solar System formation',
    erd: 100,
    description: 'Our Solar System forms about 4.6 billion years ago from a collapsing molecular cloud and protoplanetary disk. Temperature and pressure gradients sort materials; dust and ice grow by accretion into planetesimals and embryos, while some giant planets may also form through disk instability.',
    principles: ['protoplanetary disk', 'snow line + chemistry', 'core accretion', 'disk dispersal'],
  },
  {
    id: 'chemical',
    name: 'Chemical Epoch',
    subtitle: 'Matter Plus Energy',
    ageStart: 9.30,
    ageEnd: 10.20,
    focus: 'prebiotic chemical networks',
    erd: 350,
    description: 'On the young Earth, water, minerals, atmospheric chemistry, impacts, geothermal energy, and sunlight create many reaction environments. Organic chemistry is widespread, but the actual pathway from geochemistry to the first self-sustaining life remains unresolved; the simulation therefore treats protocell-like organization as a contingent model outcome, not a known historical sequence.',
    principles: ['CHNOPS + water', 'nonequilibrium chemistry', 'compartments + catalysis', 'origin of life uncertain'],
  },
  {
    id: 'biological',
    name: 'Biological Epoch',
    subtitle: 'Complexity Sustained',
    ageStart: 10.20,
    ageEnd: 13.794,
    focus: 'evolving biosphere',
    erd: 1_000,
    description: 'Evidence places thriving life on Earth well over 3.5 billion years ago. Mutation, inheritance, natural selection, drift, symbiosis, metabolism, and ecological feedback diversify lineages. Photosynthesis reshapes planetary chemistry; atmospheric oxygen rises dramatically around 2.4 billion years ago, and multicellular ecosystems appear much later.',
    principles: ['metabolism + heredity', 'selection + drift', 'oxygenation', 'ecological coevolution'],
  },
  {
    id: 'cultural',
    name: 'Cultural Epoch',
    subtitle: 'Intelligence to Technology',
    ageStart: 13.794,
    ageEnd: UNIVERSE_AGE_GYR,
    focus: 'human cultural evolution',
    erd: 1_000_000,
    description: 'The human lineage evolves over roughly six million years, with traits emerging at different times rather than as a single jump. Tool traditions are millions of years old; Homo sapiens appears about 300,000 years ago; agriculture transforms landscapes in the last ~12,000 years; industrial technology compresses change into centuries.',
    principles: ['cumulative culture', 'symbolic learning', 'technology', 'planetary-scale feedback'],
  },
];

export const STRUCTURES = [
  ['atoms', 'Neutral atoms'],
  ['halos', 'Bound halos / cosmic web'],
  ['stars', 'Stars'],
  ['planets', 'Planetary systems'],
  ['chemistry', 'Complex chemical networks'],
  ['life', 'Life'],
  ['culture', 'Technological culture'],
];

// Display-timeline milestones. These mark the visual narrative, while the event
// copy keeps uncertainty explicit where the underlying science is unresolved.
export const MILESTONES = {
  nuclei: { at: 0.055, text: 'Within minutes, Big Bang nucleosynthesis leaves mostly hydrogen and helium nuclei, plus traces of lithium.' },
  recombination: { at: 0.136, text: 'At ~380,000 years, recombination makes the universe transparent and releases the CMB.' },
  haloSeed: { at: 0.205, text: 'Primordial density fluctuations grow into bound dark-matter-dominated halos.' },
  firstStars: { at: 0.292, text: 'Roughly 100–200 million years after the Big Bang, the first stars begin to ignite.' },
  enrichment: { at: 0.365, text: 'Stellar evolution begins enriching interstellar gas with heavier elements.' },
  solarDisk: { at: 0.438, text: 'About 4.6 billion years ago, the solar nebula collapses into a rotating protoplanetary disk.' },
  earth: { at: 0.548, text: 'Rocky embryos collide and differentiate; an early Earth emerges from the inner disk.' },
  chemistry: { at: 0.625, text: 'A cooling, watery Earth sustains diverse nonequilibrium organic chemistry.' },
  protocell: { at: 0.695, text: 'In this modeled universe, persistent compartmentalized chemical networks appear.' },
  life: { at: 0.735, text: 'A self-maintaining reproducing lineage crosses the simulation’s operational life threshold.' },
  photosynthesis: { at: 0.792, text: 'Photosynthetic metabolisms expand access to stellar energy and alter biogeochemical cycles.' },
  oxygenation: { at: 0.835, text: 'Around 2.4 billion years ago, atmospheric oxygen rises sharply during the Great Oxidation Event.' },
  multicellular: { at: 0.875, text: 'Multicellular lineages and more complex ecosystems diversify.' },
  hominins: { at: 0.930, text: 'The human lineage develops through a branching hominin history spanning roughly six million years.' },
  tools: { at: 0.955, text: 'Stone-tool traditions become a durable form of cumulative behavior.' },
  sapiens: { at: 0.978, text: 'Homo sapiens appears in Africa roughly 300,000 years ago.' },
  agriculture: { at: 0.993, text: 'Within the last ~12,000 years, agriculture greatly increases human control of ecosystems and energy flows.' },
  industry: { at: 0.999, text: 'Industrial civilization rapidly amplifies energy use, information processing, and planetary feedback.' },
};

export const TRANSITIONS = [
  'plasma → transparent universe',
  'cosmic web → star-forming halos',
  'galaxy → protoplanetary disk',
  'planet formation → young Earth',
  'prebiotic chemistry → biosphere',
  'biosphere → technological planet',
];
