export const EPOCHS = [
  {
    id: 'particle',
    name: 'Particle Epoch',
    subtitle: 'Simplicity Fleeting',
    ageStart: 0,
    ageEnd: 0.001,
    focus: 'primordial plasma',
    erd: 0.02,
    description: 'Expansion and cooling carry the universe away from its earliest hot, dense, nearly equilibrated state. Matter and radiation eventually decouple, leaving persistent atoms, a growing thermal gradient, and the first usable departures from equilibrium.',
    principles: ['expansion + cooling', 'matter–radiation decoupling', 'symmetry breaking', 'energy gradients'],
  },
  {
    id: 'galactic',
    name: 'Galactic Epoch',
    subtitle: 'Hierarchy of Structures',
    ageStart: 0.001,
    ageEnd: 0.32,
    focus: 'galactic structures',
    erd: 0.5,
    description: 'Small density irregularities compete with expansion and dissipation. Gravity amplifies a surviving subset, dark-matter-like scaffolding assists collapse, and repeated mergers build a hierarchy from small protogalactic clumps toward larger galaxies and a filamentary cosmic web.',
    principles: ['density fluctuations', 'gravity', 'hierarchical clustering', 'mergers + pruning'],
  },
  {
    id: 'stellar',
    name: 'Stellar Epoch',
    subtitle: 'Forges for Elements',
    ageStart: 0.32,
    ageEnd: 8.8,
    focus: 'stars',
    erd: 1,
    description: 'Cooler, denser galactic gas fragments into stars. Gravity contracts clouds until fusion ignites. Stellar birth, maturity, and death recycle matter; massive stars and supernovae manufacture and disperse heavy elements that enrich later generations.',
    principles: ['cloud collapse', 'fusion', 'stellar lifecycles', 'nucleosynthesis'],
  },
  {
    id: 'planetary',
    name: 'Planetary Epoch',
    subtitle: 'Habitats for Life',
    ageStart: 8.8,
    ageEnd: 9.45,
    focus: 'planetary climates',
    erd: 100,
    description: 'Metal-enriched disks around young stars cool into strong compositional gradients. Dust and ice collide, stick, and accrete bottom-up into planetesimals and planets. Many disks fail; the survivors differentiate into varied rocky and gaseous worlds.',
    principles: ['protoplanetary disks', 'temperature gradients', 'accretion', 'planetary selection'],
  },
  {
    id: 'chemical',
    name: 'Chemical Epoch',
    subtitle: 'Matter Plus Energy',
    ageStart: 9.45,
    ageEnd: 10.05,
    focus: 'chemical networks',
    erd: 350,
    description: 'On suitable worlds, heavy elements, liquid environments, and recurring energy inputs drive chemistry away from equilibrium. Random encounters are constrained by bonding rules and stability, allowing some molecular networks to persist, complexify, and approach protocellular organization.',
    principles: ['prebiotic chemistry', 'chemical selection', 'energy windows', 'protocells'],
  },
  {
    id: 'biological',
    name: 'Biological Epoch',
    subtitle: 'Complexity Sustained',
    ageStart: 10.05,
    ageEnd: 13.99999,
    focus: 'living systems',
    erd: 1000,
    description: 'Life maintains organized structure by continually processing matter and energy. Variation, inheritance, adaptation, extinction, photosynthesis, metabolism, multicellularity, and nervous systems let some lineages occupy progressively richer energy-processing niches without making evolution predetermined.',
    principles: ['metabolism', 'variation + inheritance', 'natural selection', 'ecosystem energy flow'],
  },
  {
    id: 'cultural',
    name: 'Cultural Epoch',
    subtitle: 'Intelligence to Technology',
    ageStart: 13.99999,
    ageEnd: 14,
    focus: 'technological civilization',
    erd: 1_000_000,
    description: 'Symbolic intelligence, tools, communication, institutions, and technology accelerate change. Culture becomes a powerful selection system of its own while civilization captures, stores, transfers, and concentrates energy at rates far above earlier natural structures.',
    principles: ['intelligence', 'cultural selection', 'technology', 'accelerated energy capture'],
  },
];

export const STRUCTURES = [
  ['atoms', 'Neutral atoms'],
  ['galaxies', 'Galaxies'],
  ['stars', 'Stars'],
  ['planets', 'Planets'],
  ['chemistry', 'Complex chemistry'],
  ['life', 'Life'],
  ['culture', 'Technological culture'],
];

export const MILESTONES = {
  decoupling: { at: 0.11, text: 'Matter and radiation decouple; a durable thermal gradient appears.' },
  galaxySeed: { at: 0.19, text: 'A density fluctuation survives dissipation and begins gravitational collapse.' },
  galaxy: { at: 0.27, text: 'Hierarchical merging produces the first persistent galaxy-scale structure.' },
  star: { at: 0.36, text: 'A dense galactic cloud contracts until a star ignites.' },
  supernova: { at: 0.42, text: 'A massive star dies and enriches its surroundings with heavy elements.' },
  planet: { at: 0.52, text: 'A metal-rich circumstellar disk assembles a stable planetary system.' },
  chemistry: { at: 0.63, text: 'A temperate world sustains persistent, energy-fed chemical networks.' },
  protocell: { at: 0.69, text: 'Molecular selection yields protocell-like compartments.' },
  life: { at: 0.76, text: 'A self-maintaining, reproducing lineage crosses the simulation’s life threshold.' },
  photosynthesis: { at: 0.82, text: 'A lineage evolves a new way to harvest stellar energy.' },
  multicellular: { at: 0.88, text: 'Cooperative multicellular organisms diversify.' },
  intelligence: { at: 0.95, text: 'A lineage develops high-bandwidth learning and symbolic intelligence.' },
  culture: { at: 0.985, text: 'Culture begins changing the environment faster than genes alone can.' },
  technology: { at: 0.997, text: 'Technological systems concentrate energy and information on planetary scales.' },
};
